[workspace]
members = [
  "programs/vault",
  "programs/game",
  "programs/prize",
  "programs/oracle",
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
vault = "5D2EFjnokFHzGeVQ2AMpdMC6SazYaashKHAzMGWRzJVd"
game = "8CLxjoAivuuxrFNK8aanU2f6Nw7L6tBT2xEgNNoUMmNE"
prize = "FWQ8Z7RZt3wEbw4PT5ovZG2Nd4NBRtfkJn2kRD8ctH3o"
oracle = "DXcVaNoHXgykgpNvrS8s3LJFEfkW4LPayeKyVcrJP578"



[programs.localnet]
vault = "5D2EFjnokFHzGeVQ2AMpdMC6SazYaashKHAzMGWRzJVd"
game = "8CLxjoAivuuxrFNK8aanU2f6Nw7L6tBT2xEgNNoUMmNE"
prize = "FWQ8Z7RZt3wEbw4PT5ovZG2Nd4NBRtfkJn2kRD8ctH3o"
oracle = "DXcVaNoHXgykgpNvrS8s3LJFEfkW4LPayeKyVcrJP578"


[scripts]
test = "node tests/test.js"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false
